services:
  postgres:
    image: postgres:16-alpine
    container_name: shopstream-postgres
    environment:
      POSTGRES_DB: shopstream
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shopstream-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: ShopStream.Api/Dockerfile
    container_name: shopstream-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=shopstream;Username=postgres;Password=postgres
      - Jwt__Key=ShopStreamSecretKeyForJWTTokenGeneration2024!
      - Jwt__Issuer=ShopStreamAPI
      - Jwt__Audience=ShopStreamClient
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shopstream-frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  postgres_data:
